# -*- coding: utf-8 -*-
"""4110E111_1004.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11QMBPG6TlRZLOoD5N5TkWr8Fx1yGjA0R
"""

x = input('Enter your name: ')
print('Hello, '+ x)

a = int(input("請輸入: "))
a

b = a + 1
b